language: java

cache:
  directories:
    - $HOME/.m2/repository

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

script:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN